---
title: "scoringRules"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Test Scoring Rules


```{r}
library("scoringRules")
```

Example 1
```{r}
X <- matrix(seq(1:12), nrow = 4, ncol = 3)
obs = c(0,1,2,3)
es_sample(obs, dat = X)

print(X)
print(obs)
```

```{r}
energyscore = es_sample(obs, dat = X)
variogramscore = vs_sample(obs, X, w = NULL, p = 0.5)
variogramscore
```

energy score =  `r energyscore`

variogram score = `r variogramscore`


```{r}
X <- matrix(seq(1:30), nrow = 3, ncol = 10)
obs = c(1,1,2)
print(X)
print(obs)
energyscore = es_sample(obs, dat = X)
variogramscore = vs_sample(obs, X, w = NULL, p = 0.5)
```
energy score =  `r energyscore`

variogram score = `r variogramscore`

###  0Discrete data


```{r}
?crps_binom

```


```{r}
obs= c(1,1,0)
X = c(0.5,0.1,0.1)
crps_binom(y = obs, prob=X, size=3)
m = 100000
crps_binom(y = obs, prob=X, size=m)/m
```

```{r}
m = 1000000
crps_binom(y = obs, prob=X, size=m)/m
```

```{r}
size=3
x <- seq.int(0, size, 1)
prob = c(0.5,0.1,0.1)
w <- dbinom(x, size, prob)
w
a <- pbinom(x, size, prob) - 0.5 * w
2 * sum(w * ((y < x) - a) * (x - y))
```
