---
title: "Binary Data Plots"
author: "Konstantinos Vamvourellis"
date: "10/23/2019"
output:
  html_document:
    df_print: paged
    fig_caption: yes
    fig_height: 10
    fig_width: 10
    number_sections: no
    theme: lumen
    toc: yes
    toc_depth: 1
    toc_float: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library('ggplot2')
library('dplyr')
library('tidyr')
library('ggthemes')
library('scales')
library('readr')
library('forcats')
```

## Posterior Samples Plots

```{r}
df <- read_csv("log/plot_data/binary/exp1_model2.csv") %>%
  mutate(error = data - mean, 
         index = factor(1:n()))
pr_zero <-as.numeric(quantile(rnorm(10000, mean = 0, sd = 0.1),
                              probs = c(.025, 0.975)))
pr_free <-as.numeric(quantile(rnorm(10000),
                              probs = c(.025, 0.975)))
df<- df %>%
  mutate(prior1 =  case_when(
    index %in% c('2', '3', '11', '12') ~ pr_free[1],
    index %in% c('1','10') ~ 1,
    TRUE ~ pr_zero[1]),
    prior2 =  case_when(
      index %in% c('2', '3', '11', '12') ~ pr_free[2],
      index %in% c('1','10') ~ 1,
      TRUE ~ pr_zero[2]),
  )

labels = paste0('item(' ,df$J,',', df$K, ')')

# post_color <- '#28ad8c'
# post_color <- '#020f4d'
post_color <- '#3e6cc2'
# data_color <-'#d45842'
data_color <-'#ab47bf'


ggplot(df) +
  theme_economist_white(gray_bg = F)+
  geom_segment(aes(x = `q2.5` , xend = `q97.5`, y=index, yend=index),
               color = post_color, size = 1.5, alpha = 0.6) +
  geom_segment(aes(x = prior1 , xend = prior2, y=index, yend=index),
               color = post_color, size = .7, alpha = 0.5) +
  # geom_point(aes(y=index, x=prior1), shape=3, color = post_color, alpha=.5)+
  # geom_point(aes(y=index, x=prior2), shape=3, color = post_color, alpha=.5)+
  geom_point(aes(y=index, x=mean), color = post_color, alpha=.5, size = 2.5)+
  geom_point(aes(y=index, x=data), shape=24, fill =data_color, color =  data_color, alpha=.5, size = 2.5)+
  scale_y_discrete(labels = labels)+
  scale_x_continuous(breaks = pretty_breaks(6),
                     expand = c(.1,0.1))+
  scale_colour_manual(values = c(post_color, data_color),
                      labels = c("data", "data2"))+
  theme(legend.position = 'none',
        axis.text = element_text(size=12),
        axis.title = element_blank(),
        axis.ticks.length = unit( 10 * 0.5, "points"),
        panel.grid = element_blank(),
        # panel.grid.major.x = element_blank(),
        panel.grid.major.x = element_line(colour = "grey90", size = rel(.5)),
        panel.grid.major.y = element_line(colour = "grey90", size = rel(.5)),
        axis.text.y = element_text(hjust = .8,
                                   color= 'grey40'),
        axis.text.x = element_text(hjust = 0.5,
                                   color= 'grey40'),
        plot.title = element_text(family = "Verdana")) 


# ggsave("doc/bin_exp1.png", width = 10, height = 12, units = "cm")
```



## R Markdown

```{r}
df <- read_csv("./log/plot_data/lsat_heatmap_data.csv") 
colnames <- as.character(paste0('', seq(1:5)))
names(df) <- colnames

plot_data<-tibble::rowid_to_column(df, "ID") %>%
  gather(var, val, -ID) %>%
  mutate(var = fct_relevel( var, colnames))
```

## Including Plots


```{r}
ggplot(plot_data , aes(var, ID)) +
  geom_tile(aes(fill = val), colour = "white") +
  scale_fill_gradient2()+
  guides(fill = guide_colourbar(barwidth = 0.5, barheight = 10))+
  theme_economist_white(gray_bg = F, horizontal = F) +
  scale_y_discrete(breaks = pretty_breaks(10),
                   expand = c(0,0),
                   reverse_trans())+
theme(axis.text = element_text(size=6),
      legend.position = 'right',
      legend.title=element_blank(),
      legend.spacing.x = unit(.1, 'cm'),
      legend.key.size = unit(1, "cm"),
      legend.text = element_text(size = 6),
      axis.title = element_blank(),
      axis.ticks.length = unit( 10 * 0.5, "points"),
      panel.grid = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(),
      axis.text.y = element_text(hjust = .8,
                                 color= 'grey40'),
      axis.text.x = element_text(hjust = 0.5,
                                 color= 'grey40'),
      plot.title = element_text(size = 6),
      plot.subtitle = element_text(size = 6)
)
```

```{r}
ggplot(plot_data, aes(var, ID)) +
  geom_tile(aes(fill = abs(val)), colour = "white") +
  scale_fill_gradient(low = '#120a0b', high = '#f5425a' )+
  # scale_fill_gradient(low = "#ffffff", high = "#e02f38")+
  # guides(fill = guide_colourbar(barwidth = 0.7, barheight = 10))+
  theme_economist_white(gray_bg = F, horizontal = F) +
  scale_y_discrete(breaks = pretty_breaks(10),
                   expand = c(0,0),
                   reverse_trans())+
  theme(axis.text = element_text(size=10),
        legend.position = 'right',
        legend.title=element_blank(),
        legend.spacing.x = unit(.1, 'cm'),
        legend.key.size = unit(1, "cm"),
        legend.text = element_text(size = 10),
        axis.title = element_blank(),
        axis.ticks.length = unit( 10 * 0.5, "points"),
        panel.grid = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(),
        axis.text.y = element_text(hjust = .8,
                                   color= 'grey40'),
        axis.text.x = element_text(hjust = 0.5,
                                   color= 'grey40'),
        plot.title = element_text(size = 10),
        plot.subtitle = element_text(size = 10)
  )

```

```{r}
# ggsave("act1.pdf", width = 8, height = 12, units = "cm")
# ggsave("act1.png", width = 8, height = 12, units = "cm")
```

